define([
  "nablarch/ui/Widget"
, "nablarch/ui/Placeholder"
, "nablarch/ui/Collapsible"
, "nablarch/ui/DatePicker"
, "nablarch/ui/device/ios-viewport-scaling-fix"
, "nablarch/ui/device/ios-virtual-keyboard-fix"
, "nablarch/ui/event/AjaxAction"
, "nablarch/ui/event/Listener"
, "nablarch/ui/event/RevertValue"
, "nablarch/ui/event/ShowDialogAction"
, "nablarch/ui/event/SubWindowListener"
, "nablarch/ui/event/TogglePropertyAction"
, "nablarch/ui/event/WindowCloseAction"
, "nablarch/ui/event/WriteAction"
, "nablarch/ui/event"
, "nablarch/ui/ListBuilder"
, "nablarch/ui/AutoSum"
, "nablarch/ui/readonly"
, "nablarch/ui/ResponsibleImage"
, "nablarch/ui/selector"
, "nablarch/ui/Tab"
, "nablarch/ui/TabindexOrder"
, "nablarch/ui/TabLink"
, "nablarch/ui/ToggleCheckbox"
, "nablarch/ui/TreeList"
, "nablarch/ui/TreeMenu"
, "nablarch/ui/AutoSpan"
, "nablarch/ui"
, "nablarch/util/BigDecimal"
, "nablarch/util/Consumer"
, "nablarch/util/DateUtil"
, "nablarch/util/SimpleDateFormat"
, "nablarch/util"
], function(Widget) { "use strict"; return { Widget: Widget }; });
