DROP TABLE UGROUP_SYSTEM_ACCOUNT
;
DROP TABLE UGROUP_AUTHORITY
;
DROP TABLE UGROUP
;
DROP TABLE PERMISSION_UNIT_REQUEST
;
DROP TABLE REQUEST
;
DROP TABLE SYSTEM_ACCOUNT_AUTHORITY
;
DROP TABLE USERS
;
DROP TABLE PERMISSION_UNIT
;
DROP TABLE SYSTEM_ACCOUNT
;
DROP TABLE ID_GENERATE
;
DROP TABLE MESSAGE
;
DROP TABLE BUSINESS_DATE
;
DROP TABLE CODE_PATTERN
;
DROP TABLE CODE_NAME
;
DROP TABLE DELETE_USER_REPORT_TEMP
;
DROP TABLE BATCH_REQUEST
;
DROP TABLE USER_INFO_TEMP
;
DROP TABLE MAIL_ATTACHED_FILE
;
DROP TABLE MAIL_RECIPIENT
;
DROP TABLE MAIL_TEMPLATE
;
DROP TABLE MAIL_REQUEST
;
DROP TABLE DELETE_USER_SEND_MESSAGE
;
DROP TABLE SENT_MESSAGE
;
DROP TABLE VALIDATION_SAMPLE_INFO
;
DROP TABLE FORMATTER_SAMPLE_INFO
;
DROP TABLE IMG_FILE_INFO
;
DROP SEQUENCE USER_ID_SEQ
;
DROP SEQUENCE USER_INFO_ID_SEQ
;
DROP SEQUENCE SEND_MESSAGE_SEQ
;